name: Setup Just
description: Setup Just

runs:
  using: composite
  steps:
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
      with:
        just-version: '1.45.0'
