name: Setup Bun
description: Setup Bun

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      with:
        bun-version-file: '.bun-version'

    - name: Get bun cache directory
      id: bun-cache
      shell: bash
      run: |
        echo "dir=$(bun pm cache)" >> $GITHUB_OUTPUT

    - name: Setup bun cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ steps.bun-cache.outputs.dir }}
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install Node Modules
      shell: bash
      run: bun install --frozen-lockfile
